@extends('layouts.admin')

@section('content')
<div class="d-flex justify-content-between align-items-center mb-4"><div><h2 class="section-heading mb-1">Incident & Response History</h2><p class="section-excerpt mb-0">Completed and archived government records remain searchable for accountability and audit purposes.</p></div><button onclick="window.print()" class="btn btn-outline-dark"><i class="bi bi-printer"></i> Print History</button></div>
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
<div class="card border-0 shadow-sm mb-4"><div class="card-body"><form class="row g-2"><div class="col-md-5"><input name="search" value="{{ request('search') }}" class="form-control" placeholder="Incident no., reporter, location"></div><div class="col-md-3"><input type="date" name="start_date" value="{{ request('start_date') }}" class="form-control"></div><div class="col-md-3"><input type="date" name="end_date" value="{{ request('end_date') }}" class="form-control"></div><div class="col-md-1"><button class="btn btn-primary w-100">Go</button></div></form></div></div>
<div class="card shadow-sm border-0"><div class="table-responsive"><table class="table align-middle mb-0"><thead class="table-light"><tr><th>Incident</th><th>Priority</th><th>Driver</th><th>Ambulance</th><th>Status</th><th>Attachments</th><th>Completed/Archived</th><th></th></tr></thead><tbody>@forelse($history as $incident)<tr><td>{{ $incident->incident_number }}</td><td>{{ $incident->priority }}</td><td>{{ $incident->driver?->user?->name ?? 'Unassigned' }}</td><td>{{ $incident->ambulance?->plate_number ?? 'Unassigned' }}</td><td><span class="badge bg-{{ $incident->archived_at ? 'dark' : 'success' }}">{{ $incident->archived_at ? 'Archived' : ucfirst($incident->status) }}</span></td><td>{{ $incident->attachments->count() }}</td><td>{{ ($incident->archived_at ?: $incident->updated_at)?->format('M d, Y h:i A') }}</td><td><a href="{{ route('admin.incidents.show',$incident) }}" class="btn btn-sm btn-outline-primary">View</a></td></tr>@empty<tr><td colspan="8" class="text-center text-muted py-4">No history records found.</td></tr>@endforelse</tbody></table></div></div>
<style media="print">.admin-sidebar,.btn,form{display:none!important}body{background:#fff!important}</style>
@endsection
